<template>
  <section class="about">
    <div class="about__container">
      <PageHeader
        eyebrow="About"
        title="Yannosay Resources"
        lede="A free library of assets published by Yannosay Productions."
      />

      <article class="prose about__body">
        <h2>What this is</h2>
        <p>
          Yannosay Resources is a public library of files published by Yannosay
          Productions. Images, audio, code, templates, and reference documents
          live here, available to download without an account, without tracking,
          and without paywalls.
        </p>

        <h2>Why we publish</h2>
        <p>
          Most of what we make starts as a tool for our own projects. Rather
          than leave it in a private folder, we publish the parts that are
          useful on their own — textures, loops, snippets, and templates —
          under licenses that let anyone use, modify, and redistribute them.
        </p>
        <p>
          This is not a marketplace. Nothing here is for sale. Nothing here
          requires an account. There is no advertising, no analytics, and no
          third-party tracking. Downloads are counted at the moment a file is
          requested, and that count is the only data this site stores about
          visitors.
        </p>

        <h2>What we publish</h2>
        <ul>
          <li><strong>Images</strong> — illustrations, textures, and graphics.</li>
          <li><strong>Audio</strong> — music, loops, and sound effects.</li>
          <li><strong>Video</strong> — motion clips and overlays.</li>
          <li><strong>Code</strong> — scripts, libraries, and reusable snippets.</li>
          <li><strong>Templates</strong> — starting points for creative work.</li>
          <li><strong>Documents</strong> — guides, references, and PDFs.</li>
          <li><strong>Fonts</strong> — typefaces we have made or licensed.</li>
          <li><strong>Archives</strong> — bundled collections and resource packs.</li>
        </ul>

        <h2>Licensing</h2>
        <p>
          Every resource lists its own license on its detail page. Most are
          released under Creative Commons Attribution (CC-BY 4.0), the MIT
          License, or the Apache 2.0 License. Some are released into the
          public domain under CC0. Check the specific resource before you use
          it in a commercial project.
        </p>
        <p>
          Where a license requires attribution, credit
          &ldquo;Yannosay Productions&rdquo; and link back to this site.
          Full licensing terms are on the
          <NuxtLink to="/legal/license">Licensing page</NuxtLink>.
        </p>

        <h2>What we do not publish</h2>
        <p>
          We do not publish assets that were generated by AI models, either
          wholesale or as a starting point. Every illustration, every musical
          loop, every line of code on this site was made by a human. This is
          a deliberate choice, not an accident of process. The full reasoning
          is on the <a href="https://yannosay.com/ai">AI Usage Policy</a>.
        </p>

        <h2>Reporting a problem</h2>
        <p>
          If a resource is broken, mislabeled, or infringes on your rights,
          see the <NuxtLink to="/legal/dmca">DMCA &amp; Takedown</NuxtLink>
          page or <NuxtLink to="/contact">contact us</NuxtLink>.
        </p>
      </article>
    </div>
  </section>
</template>

<script setup lang="ts">
import PageHeader from '~/components/ui/PageHeader.vue'

useCanonical('/about')

useHead({
  title: 'About',
  meta: [
    { name: 'description', content: 'About Yannosay Resources — a free library of assets published by Yannosay Productions.' },
    { property: 'og:title', content: 'About Yannosay Resources' },
    { property: 'og:description', content: 'A free library of assets published by Yannosay Productions.' }
  ]
})
</script>

<style lang="scss" scoped>
@use '~/assets/css/components/page' as page;

.about {
  @include page.page;
  min-height: 100svh;
}

.about__container {
  max-width: 48rem;
  margin: 0 auto;
}

.about__body {
  margin-top: 2rem;
}
</style>